# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5083f4393225e0f6421ce1de66a4f3acccc7e83de62f2f83dd4ce8cb69155ce94e28365063cf79c2134408ead312c339ef14d3b58227f373f5c20a9b6a764e7

test:
  secret_key_base: fd10fbafd1c5129bf49398730733507d933b6c4bb1c79ba537b9f8cb496dc239bd96568454e17f7204f4b5c185c5d0cc87d15bef57f2d84e24420af725034be9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
